name: Publish Docker Image
description: Publish Docker image for a new version.

on:
  workflow_call:
    inputs:
      version:
        description: 'Release version Format: x.y.z-[alpha|beta|pre].n'
        required: true
        type: string
      pre_release:
        description: 'Is this a pre-release?'
        required: false
        default: false
        type: boolean

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    FULL_IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Environment
          uses: ./.github/workflows/setup

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.PAT }}

        - name: Extract Docker Metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.FULL_IMAGE_NAME }}

        - name: Build Binary
          run: bun compile linux-x64-baseline ${{ inputs.version }}
        
        - name: Build and Push Docker Image
          uses: docker/build-push-action@v2
          with:
                context: ./docker
                push: true
                tags: |
                    ${{ env.FULL_IMAGE_NAME }}:${{ inputs.version }}
                    if ${{ inputs.pre_release }}; then
                        ${{ env.FULL_IMAGE_NAME }}:${{ inputs.version }}-pre
                    fi
                labels: |
                org.opencontainers.image.title=${{ env.IMAGE_NAME }}
                org.opencontainers.image.version=${{ inputs.version }}
                org.opencontainers.image.revision=${{ github.sha }}
                org.opencontainers.image.created=${{ steps.meta.outputs.created }}
                org.opencontainers.image.authors=${{ steps.meta.outputs.authors }}
                org.opencontainers.image.url=${{ steps.meta.outputs.url }}


        
