name: Setup Environment
description: Set up code, dependencies, and patches.
runs:
  using: "composite"
  steps:

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      shell: bash
      run: bun install
