name: Create Release
description: Create Release and attach binaries for a new version.

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version Format: x.y.z-[alpha|beta|pre].n'
        required: true
        type: string
      release_name:
        description: 'Release title'
        required: true
        type: string
      release_notes:
        description: 'Release notes or changelog'
        required: true
        type: string
      pre_release:
        description: 'Is this a pre-release?'
        required: false
        default: false
        type: boolean

jobs:
  
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.event.inputs.version }}

  docker-publish:
    uses: ./.github/workflows/docker-publish-main.yml
    with:
      version: ${{ github.event.inputs.version }}
      pre_release: ${{ github.event.inputs.pre_release }}
    permissions:
      contents: read
      packages: write

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: binaries
        path: ./binaries

    - name: Create GitHub Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ github.event.inputs.version }}
        name: ${{ github.event.inputs.release_name }}
        body: ${{ github.event.inputs.release_notes }}
        prerelease: ${{ github.event.inputs.pre_release }}
        artifacts: ./binaries/*
