name: Test
description: Run tests on the codebase.

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/workflows/setup

    - name: Run tests
      run: bun test
